### ISSUE TITLE
Poor performance on load

### ISSUE THREAD

**Issue by divergentdave** [cmgiven/justgrimes#8]
When I load justgrimes.review, the page hangs for 5-7 seconds while past ratings load. Profiling indicates most of the time is being spent in animation methods. It looks like [this timer](https://github.com/cmgiven/justgrimes/blob/9dba3dcc38aca7e65a0c6355715454c54ef3726c/justgrimes-review.js#L12) isn't long enough to span loading ratings, and then all the chart updates from loading historical data pile up. I don't really understand JS data binding or Meteor JS, so I'm afraid I don't have any suggestions.

**Comment by cmgiven** [comment]
True. That timer was a dumb solution anyway. Added an [80ms debounce function](https://github.com/cmgiven/justgrimes/commit/2e44ccdb8eba560a8d89ff2f71683d43fe2e2ce1); that appears to solve it.

**Comment by justgrimes** [comment]
@cmgiven thank you for making this app great again.
